### ISSUE TITLE
Sidebar not visible ?

### ISSUE THREAD

**Issue by bakman2** [bartbutenaers/node-red-autolayout-sidebar#6]
Installed via palette and restarted NR - sidebar not showing up, retried via cli, same result.

node v18.19.0
npm 9.2.0
node-red 3.1.0

<img width="579" alt="image" src="https://github.com/user-attachments/assets/301f114a-71a7-4f11-b80e-b95715a42d4d">

<img width="310" alt="image" src="https://github.com/user-attachments/assets/39bf5a4d-7b55-4f34-8b6b-e457d4a38354">

**Comment by bartbutenaers** [comment]
@bakman2,
I am running currently Node-RED v3.1.3 (NodeJs v18.19.0) and just installed it without problems.
Are there perhaps any errors in your browser console log?
Bart

**Comment by gorenje** [comment]
Deploying multiple times helps. The way the sidebars are initialised requires multiple deploys before the sidebar appears.
 
This is related to the event handling in older versions of node red especially 3.1.0

**Comment by bartbutenaers** [comment]
Hi @gorenje,
I see that you are alive and kicking ;-)
Thanks for joining!

**Comment by gorenje** [comment]
:) of course, still around! Working on another node idea …

**Comment by bakman2** [comment]
> Deploying multiple times helps. 

Indeed, this was it, thanks!

**Comment by gorenje** [comment]
For those that come after me, this is the [PR](https://github.com/node-red/node-red/pull/4484) that fixed this behaviour. It was rolled out with [3.1.4](https://github.com/node-red/node-red/releases?page=2).

**Comment by bakman2** [comment]
@gorenje I shall upgrade sir ;) thanks
